services:
  empacotamento:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    networks:
      - empacotamento_net
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus:v3.4.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/resources/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  empacotamento_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local 
